modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="creeper"
version="1.0.0"
displayName="Creeper+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BenGFly, MCreator"

[[dependencies.creeper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




